

#ifndef COMMON_ENUM_H

#define COMMON_ENUM_H

enum MT5_LANGUAGE_NUMBER
{
	EN,
	JP,
	OTHERS
};

enum Error_Code_Value {

	CUSTOM_ERROR_CODE_NONE_ONLY_EA = 1,                   //1
	CUSTOM_ERROR_CODE_FAILED_ONTIMER,                     //2
	CUSTOM_ERROR_CODE_NONE_TRADW_ALLOWED,                 //3
	CUSTOM_ERROR_CODE_FAILED_LANGUAGE_SETING,             //4
	CUSTOM_ERROR_CODE_INPUT_FAILED_STRING_NONE_NUMBER,    //5
	CUSTOM_ERROR_CODE_INPUT_FAILED_STRING_LENGTH,         //6
	CUSTOM_ERROR_CODE_INPUT_FAILED_MAX_TRADE,             //7
	CUSTOM_ERROR_CODE_INPUT_FAILED_WAIT_TIME,             //8
	CUSTOM_ERROR_CODE_INPUT_FAILED_INDICATOR_VALUE,       //9
	CUSTOM_ERROR_CODE_INPUT_FAILED_PERCENTAGE_VALUE,      //10
	CUSTOM_ERROR_CODE_INPUT_FAILED_FIXID_VALUE,           //11
	CUSTOM_ERROR_CODE_INPUT_FAILED_COMMISION_USD_VALUE,   //12
	CUSTOM_ERROR_CODE_INPUT_FAILED_GMT_VALUE,             //13
	CUSTOM_ERROR_CODE_ONTIMRE_NOT_SUCCEDDED,              //14
	CUSTOM_ERROR_CODE_INPUT_TIME_VALUE_FAILED,            //15
	CUSTOM_ERROR_CODE_FAILED_APP_EXIST,                   //16
	CUSTOM_ERROR_CODE_FAILED_WATCH_EXIST,                 //17
	CUSTOM_ERROR_CODE_FRAUD_SL_FILE,                      //18
	CUSTOM_ERROR_CODE_FAILED_CREATE_LOG,                  //19
	CUSTOM_ERROR_CODE_FAILED_OPEN_LOG,                    //20
	CUSTOM_ERROR_CODE_FAILED_WRITE_LOG,                   //21
	CUSTOM_ERROR_CODE_INPUT_TIME_SET_OR_UNSET_FAILED,     //22
	CUSTOM_ERROR_CODE_INPUT_TIME_DATE_CHANGE_TIME_FAILED, //23
	CUSTOM_ERROR_CODE_LOG_DELETED,                        //24
	CUSTOM_ERROR_CODE_FAILED_APP_BOOT,                    //25
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_CREATE,              //26
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_OPEN,                //27
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_ACCESS,              //28
	CUSTOM_ERROR_CODE_NONE_ERROR_NUM_FILE,                //29
	CUSTOM_ERROR_CODE_NONE_MT5_LANGUAGE_FILE,             //30
	CUSTOM_ERROR_CODE_NONE_VISIBLE_ERROR_NUM_FILE,        //31
	CUSTOM_ERROR_CODE_UNKNOWN_ERROR,                      //32
	CUSTOM_ERROR_CODE_FRAUD_FILE_SIZE,                    //33
	CUSTOM_ERROR_CODE_FAILED_GET_DRC,                     //34
	CUSTOM_ERROR_CODE_FAILED_GET_LOCAL_APP_DRC,           //35
	CUSTOM_ERROR_CODE_FAILED_OPEN_FILE,                   //36
	CUSTOM_ERROR_CODE_FAILED_READ_FILE_BYTE_SIZE,         //37
	CUSTOM_ERROR_CODE_FAILED_WRITE_FILE_BYTE_SIZE,        //38
	CUSTOM_ERROR_CODE_FAILED_FILE_LOCK,                   //39
	CUSTOM_ERROR_CODE_FAILED_FILE_UNLOCK,                 //40
	CUSTOM_ERROR_CODE_FAILED_LOG_NONE_GET_UNKNOWN_TIME,   //41
	CUSTOM_ERROR_CODE_FAILED_CORRECT_ALIGNMENT,           //42
	CUSTOM_ERROR_CODE_FAILED_UNAVAILABLE_HANDLE_VALUE,    //43
	CUSTOM_ERROR_CODE_FAILED_ROOT_DRC,                    //44
	CUSTOM_ERROR_CODE_FAILED_FILE_LOCK_ONE,               //45
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_TIME,               //46
	CUSTOM_ERROR_CODE_FAILED_FILE_WRITE_FLASH,            //47
	CUSTOM_ERROR_CODE_FRAUD_COMMAND_LINE_VALUE,           //48
	CUSTOM_ERROR_CODE_FRAUD_CALL_NEW_PROCCESS,            //49
	CUSTOM_ERROR_CODE_FAILED_GET_ERROR_CODE_VALUE,        //50
	CUSTOM_ERROR_CODE_FRAUD_ERROR_CODE,                   //51
	CUSTOM_ERROR_CODE_FAILED_LOG_DRC_TOTAL_BYTE_SIZE,     //52
	CUSTOM_ERROR_CODE_FAILED_RUN_LOG_DELETED,             //53
	CUSTOM_ERROR_CODE_FAILED_OBJECT,                      //54
	CUSTOM_ERROR_CODE_FAILED_FILE_INIT,                   //55
	CUSTOM_ERROR_CODE_FAILED_FILE_WRITE,                  //56
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_SIZE,               //57
	CUSTOM_ERROR_CODE_FAILED_FILE_POINTER_SET,            //58
	CUSTOM_ERROR_CODE_FAILED_FILE_READ,                   //59
	CUSTOM_ERROR_CODE_FAILED_DATA_COPY,                   //60
	CUSTOM_ERROR_CODE_FAILED_GET_POSITION_DATA,           //61
	CUSTOM_ERROR_CODE_FAILED_GET_POSITION_COMMISSION,     //62
	CUSTOM_ERROR_CODE_FAILED_GET_CALC_PRICE,              //63
	CUSTOM_ERROR_CODE_FAILED_POSITION_CLOSE,              //64
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_NAME,               //65
	CUSTOM_ERROR_CODE_FAILED_FILE_EXIST,                  //66
	CUSTOM_ERROR_CODE_CREATE_NEW_FILE,                    //67
	CUSTOM_ERROR_CODE_FAILED_GET_MUTEX,                   //68
	CUSTOM_ERROR_CODE_FAILED_FILE_DELETE,                 //69
	CUSTOM_ERROR_CODE_MAX_VALUE                           //70
};

#endif