

#ifndef COMMON_ENUM_H

#define COMMON_ENUM_H

enum MT5_LANGUAGE_NUMBER
{
	EN,
	JP,
	OTHERS
};

enum Error_Code_Value {

	CUSTOM_ERROR_CODE_NONE_ONLY_EA = 1,                   //1
	CUSTOM_ERROR_CODE_NONE_TRADW_ALLOWED,                 //2
	CUSTOM_ERROR_CODE_FAILED_LANGUAGE_SETING,             //3
	CUSTOM_ERROR_CODE_INPUT_FAILED_STRING_NONE_NUMBER,    //4
	CUSTOM_ERROR_CODE_INPUT_FAILED_STRING_LENGTH,         //5
	CUSTOM_ERROR_CODE_INPUT_FAILED_MAX_TRADE,             //6
	CUSTOM_ERROR_CODE_INPUT_FAILED_WAIT_TIME,             //7
	CUSTOM_ERROR_CODE_INPUT_FAILED_INDICATOR_VALUE,       //8
	CUSTOM_ERROR_CODE_INPUT_FAILED_PERCENTAGE_VALUE,      //9
	CUSTOM_ERROR_CODE_INPUT_FAILED_FIXID_VALUE,           //10
	CUSTOM_ERROR_CODE_INPUT_FAILED_COMMISION_USD_VALUE,   //11
	CUSTOM_ERROR_CODE_INPUT_FAILED_GMT_VALUE,             //12
	CUSTOM_ERROR_CODE_ONTIMRE_NOT_SUCCEDDED,              //13
	CUSTOM_ERROR_CODE_INPUT_TIME_VALUE_FAILED,            //14
	CUSTOM_ERROR_CODE_FRAUD_SL_FILE,                      //15
	CUSTOM_ERROR_CODE_FAILED_CREATE_LOG,                  //16
	CUSTOM_ERROR_CODE_FAILED_OPEN_LOG,                    //17
	CUSTOM_ERROR_CODE_FAILED_WRITE_LOG,                   //18
	CUSTOM_ERROR_CODE_INPUT_TIME_SET_OR_UNSET_FAILED,     //19
	CUSTOM_ERROR_CODE_INPUT_TIME_DATE_CHANGE_TIME_FAILED, //20
	CUSTOM_ERROR_CODE_FAILED_LOG_DELETED,                 //21
	CUSTOM_ERROR_CODE_FAILED_APP_BOOT,                    //22
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_CREATE,              //23
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_OPEN,                //24
	CUSTOM_ERROR_CODE_FAILED_SL_FILE_ACCESS,              //25
	CUSTOM_ERROR_CODE_NONE_ERROR_NUM_FILE,                //26
	CUSTOM_ERROR_CODE_NONE_MT5_LANGUAGE_FILE,             //27
	CUSTOM_ERROR_CODE_NONE_VISIBLE_ERROR_NUM_FILE,        //28
	CUSTOM_ERROR_CODE_UNKNOWN_ERROR,                      //29
	CUSTOM_ERROR_CODE_FRAUD_FILE_SIZE,                    //30
	CUSTOM_ERROR_CODE_FAILED_GET_DRC,                     //31
	CUSTOM_ERROR_CODE_FAILED_GET_LOCAL_APP_DRC,           //32
	CUSTOM_ERROR_CODE_FAILED_OPEN_FILE,                   //33
	CUSTOM_ERROR_CODE_FAILED_WRITE_FILE_BYTE_SIZE,        //34
	CUSTOM_ERROR_CODE_FAILED_FILE_LOCK,                   //35
	CUSTOM_ERROR_CODE_FAILED_FILE_UNLOCK,                 //36
	CUSTOM_ERROR_CODE_FAILED_LOG_NONE_GET_UNKNOWN_TIME,   //37
	CUSTOM_ERROR_CODE_FAILED_ROOT_DRC,                    //38
	CUSTOM_ERROR_CODE_FAILED_FILE_LOCK_ONE,               //39
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_TIME,               //40
	CUSTOM_ERROR_CODE_FAILED_FILE_WRITE_FLASH,            //41
	CUSTOM_ERROR_CODE_FRAUD_COMMAND_LINE_VALUE,           //42
	CUSTOM_ERROR_CODE_FAILED_OBJECT,                      //43
	CUSTOM_ERROR_CODE_FAILED_FILE_INIT,                   //44
	CUSTOM_ERROR_CODE_FAILED_FILE_WRITE,                  //45
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_SIZE,               //46
	CUSTOM_ERROR_CODE_FAILED_FILE_POINTER_SET,            //47
	CUSTOM_ERROR_CODE_FAILED_FILE_READ,                   //48
	CUSTOM_ERROR_CODE_FAILED_GET_POSITION_DATA,           //49
	CUSTOM_ERROR_CODE_FAILED_GET_POSITION_COMMISSION,     //50
	CUSTOM_ERROR_CODE_FAILED_GET_CALC_PRICE,              //51
	CUSTOM_ERROR_CODE_FAILED_POSITION_CLOSE,              //52
	CUSTOM_ERROR_CODE_FAILED_GET_FILE_NAME,               //53
	CUSTOM_ERROR_CODE_CREATE_NEW_FILE,                    //54
	CUSTOM_ERROR_CODE_FAILED_APP_EXIST,                   //55
	CUSTOM_ERROR_CODE_MAX_VALUE                           //56
};

#endif